config/routes.rb
Rails.application.routes.draw do

  get 'job_seekers/new'
  get 'companies/new'
  get 'sessions/new'
  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'static_pages#signup'
  get "/signup/recruiter", to: 'recruiters#new'
  get "/signup/job_seeker", to: 'job_seekers#new'
  post "/signup/job_seeker", to: 'job_seekers#create'
  post "/signup/recruiter",  to: 'recruiters#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :recruiters
  resources :companies
  resources :job_seekers
  resources :admins, only:[:edit, :update,:show]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def signup
  end
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>Xiao Ma: xma21@ncsu.edu</p></br>
<p>Jixiong He: jhe17@ncsu.edu</p></br>
<p>Minghao Pan: mpan2@ncsu.edu</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to JALAPENO!</h1><br/>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/signup.html.erb
<% provide(:title, "Sign up") %>
<div class="center jumbotron">
<%= link_to "Sign up as a recruiter", signup_recruiter_path, class: "btn btn-lg btn-primary" %></br></br>

<%= link_to "Sign up as a job seeker", signup_job_seeker_path, class: "btn btn-lg btn-primary" %></br></br>
</div>