config/routes.rb
Rails.application.routes.draw do

  get 'job_seekers/new'
  get 'companies/new'
  get 'sessions/new'
  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'static_pages#signup'
  get "/signup/recruiter", to: 'recruiters#new'
  get "/signup/job_seeker", to: 'job_seekers#new'
  post "/signup/job_seeker", to: 'job_seekers#create'
  post "/signup/recruiter",  to: 'recruiters#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :recruiters
  resources :companies
  resources :job_seekers
  resources :admins, only:[:edit, :update,:show]
end

app/views/layouts/_admin_actions.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Actions <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Manage Recruiters", recruiters_path %></li>
    <li><%= link_to "Manage Job seekers",   "#" %></li>
    <li><%= link_to "Manage Companies",   "#" %></li>
    <li><%= link_to "Manage Jobs",   "#" %></li>
    <li><%= link_to "Manage Applications",   "#" %></li>
  </ul>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <h>Ruby on Rails Tutorial by Team 48</h>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "JALAPENO", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>

        <% if logged_in? %>
          <% if session[:identity]=="Recruiter" %>
            <%= render 'layouts/recruiter_actions' %>
          <% elsif session[:identity]=="JobSeeker" %>
            <%= render 'layouts/job_seeker_actions' %>
          <% elsif session[:identity]=="Admin" %>
            <%= render 'layouts/admin_actions' %>
          <% end%>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>

              <% if session[:identity]=="Recruiter" %>
                <li><%= link_to "Settings", edit_recruiter_path(current_user) %></li>
              <% elsif session[:identity]=="JobSeeker" %>
                <li><%= link_to "Settings", edit_job_seeker_path(current_user) %></li>
              <% elsif session[:identity]=="Admin" %>
                <li><%= link_to "Settings", edit_admin_path(current_user) %></li>
              <% end %>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_job_seeker_actions.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Actions <b class="caret"></b></a>
  <ul class="dropdown-menu">

  </ul>
</li>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_recruiter_actions.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Actions <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Choose a company", "#" %></li>
    <li><%= link_to "Create a company", "#" %></li>
    <li><%= link_to "Edit company info", "#" %></li>
    <li class="divider"></li>
    <li><%= link_to "Publish a job", "#" %></li>
    <li><%= link_to "View jobs", "#" %></li>
    <li><%= link_to "Edit jobs", "#" %></li>
    <li class="divider"></li>
    <li><%= link_to "View applications", "#" %></li>
  </ul>
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </div>
  </body>

</html>